# Generated by Django 6.0.5 on 2026-07-03 04:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_videolist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VideoList",
            new_name="VideoLike",
        ),
    ]
